// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CheckMyFlightD43Q6ATest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "D:\\tmp\\geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void checkMyFlightD43Q6A() {
        driver.get("https://www.virginatlantic.com/mytrips/findPnr.action");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.id("mbsFirstname")).click();
        driver.findElement(By.id("mbsFirstname")).sendKeys("Baosheng");
        driver.findElement(By.id("mbsLastname")).sendKeys("Sha");
        driver.findElement(By.id("mbsBookingRef")).sendKeys("D43Q6A");
        driver.findElement(By.id("findFltButtonStandAlone")).click();


        System.out.println("hi");
    }
}
